application: gif-maker-1204      # Development
# application: cs-bmo-locator-qa   # QA
# application: bmo-locator-staging     # Staging
# The production server config file is at app-production.yaml

module: frontend
runtime: python27
api_version: 1
threadsafe: true

# Scaling parameters
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: automatic


builtins:
- deferred: off

handlers:
- url: /static
  static_dir: static
- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?/scripts/.*$
- ^(.*/)?app\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~